openapi: 3.0.0
info:
  title: Bitcoin Address UTXO API
  version: 1.0.0
paths:
  /address/{address}/utxo:
    get:
      summary: Get unspent transaction outputs (UTXOs) for a Bitcoin address
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The Bitcoin address for which to retrieve UTXOs
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/utxo"
components:
  schemas:
    utxo:
      type: object
      properties:
        txid:
          type: string
          description: The transaction ID
        vout:
          type: integer
          description: The index of the output in the transaction
        status:
          type: object
          properties:
            confirmed:
              type: boolean
              description: Indicates if the transaction is confirmed
            block_height:
              type: integer
              description: The height of the block in which the transaction was included
            block_hash:
              type: string
              description: The hash of the block in which the transaction was included
            block_time:
              type: integer
              description: The timestamp of the block in which the transaction was included
        value:
          type: integer
          description: The value of the unspent output in satoshis
